# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: mozzarella-variables

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "install node.js"

  - script: |
      export AZURE_STORAGE_KEY="$(azureStorageAccount)"
      echo "$(azureStorageAccount)"
      export AZURE_STORAGE_ACCOUNT="$(azureStorageKey)"
      echo "$(azureStorageKey)"
    displayName: "setup storage credentials"

  - script: |
      npm install
    displayName: "npm install"

  - script: |
      npm run test:unit:ci
    displayName: "unit tests"

  - script: |
      npm run test:cypress:ci
    displayName: "cypress tests"

  - script: |
      npm run test:visual
    displayName: "visual tests"

  - script: |
      npm run build -- --prod
    displayName: "build application"

  - script: |
      az storage blob upload-batch --account-name="$(azureStorageAccount)" --account-key="$(azureStorageKey)" -s ./dist/mozzarella -d="\$web"
    displayName: "deploy to bucket"
